### ISSUE TITLE
can-route-pushstate should be exportable as a named export

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-route-pushstate#101]
I'd like to make it so `can-route-pushstate` can be a named export. In order to do this, it can not automatically set itself up as the default routing as is done here:

https://github.com/canjs/can-route-pushstate/blob/master/can-route-pushstate.js#L308-L311

Instead, this setup should happen if `pushstate` is called:

```js
import {route, routePushstate} from "can";


routePushstate(); // sets itself up as the routing connection

route.data = new AppVM();
route.register(" ... ");
route.start();

```

Alternatively, we could make it work with the stuff @chasenlehara is working on a little more clearly:

```js
import {route, routePushstate} from "can";

route.register(" ... ");

// bind would replace .start()
// it would effectively setup the two-way binding between route.data
route.bind(new AppVM(), routePushstate ); 
``` 

We could create a hash one that does the same thing:

```js
import {route, routeHash} from "can";

route.register(" ... ");

// bind would replace .start()
// it would effectively setup the two-way binding between route.data
route.bind(new AppVM(), routeHash ); 
```

**Comment by chasenlehara** [comment]
Here’s one more alternative (not saying it’s better, just throwing it out there):

```js
import {routePushstate as route} from "can";

route.data = new AppVM();
route.register(" ... ");
route.start();
```

**Comment by phillipskevin** [comment]
Would it be useful to have more granular control over the binding? Something like this:
```
import { routePushstate, valueBind, valueFrom } from "can";

const app = new AppVM();

valueBind(app.page, routePushstate.page);
valueFrom(app.section, routePushstate.section);
```

**Comment by matthewp** [comment]
I think pushstate should be the default. I would move pushstate into can-route core and then come up with an API to toggle between hashchange/pushstate (no good idea comes to mind immediately).

**Comment by matthewp** [comment]
route.bind() is cool too

**Comment by matthewp** [comment]
How about exporting the constructors? Why hide this from the user? So instead of having to even need `can-route` you could just import the one that you want.

```js
import RoutePushState from "can-route-pushstate";

const route = new RoutePushState();
route.register("{page}", { page: "home" });
route.start();
```

or for hashchange

```js
import RouteHash from "can-route-hash";

const route = new RouteHash();
route.register("{page}", { page: "home" });
route.start();
```

So `can-route` would become a mixin that is used by can-route-pushstate and can-route-hash, but not something the user would need to use directly.

I like his because it doesn't hide the fact that these things are "just observables". And it might make it more friendly to be used as a property on the appstate like a lot of people want to do.

```js
import { DefineMap, RoutePushState } from "can";

const AppViewModel = DefineMap.extend({
  routeData: RoutePushState,

  init() {
    this.routeData = new RoutePushState();
    this.routeData.register("{page}", { page: "home" });
    this.routeData.start();

    console.log(this.routeData.page); // -> "home"
  }
});
```

**Comment by justinbmeyer** [comment]
consider the `replaceStateOn` type methods in any API redesign ...

**Comment by matthewp** [comment]
We decided to hold off on doing a semver breaking change here. So this new API will be post-5.0.

For 5.0 we wanted to make this possible:

```js
import { routePushstate as route } from "can";

route.register(...
```

This will work once added to canjs/core. However, this means there isn't a great way to disable pushstate, for example if using a development.html or something.

The only way would be to not import routePushstate this way, but instead use `can-route-pushstate`. This is what I propose we do in DoneJS for now.

```js
import { route } from "can";
import "can-route-pushstate";

route.register(...
```

To make development.html we just need to turn `can-route-pushstate` into a noop with steal (which donejs already does).

**Comment by matthewp** [comment]
We talked about this on a hangout a couple of weeks ago. If I recall we were leaning towards going with `route.bind`, creating `can-route-hash` and having that and pushstate export their constructors, which would then be bound like:

```js
route.bind(new AppVM(), new RouteHash());
```

Question: What is the difference between `route.bind` here and can-bind?

**Comment by phillipskevin** [comment]
This is done in https://github.com/canjs/can-route-pushstate/releases/tag/v5.0.0.
