### ISSUE TITLE
anchorClickHandler should preventDefault earlier

### ISSUE THREAD

**Issue by nlundquist** [canjs/can-route-pushstate#115]
Currently in `anchorClickHandler`, if an unhandled exception occurs during state changes, execution breaks before `preventDefault` is called. The default behavior of the anchor fires, doing a full navigation / reloading the page.

This resulting situation is pretty tough to debug, so we should instead call `preventDefault` as early as possible, rather than as the last thing we do here: https://github.com/canjs/can-route-pushstate/blob/83559504238e01c589646382261a33f5efa5bd18/can-route-pushstate.js#L202

**Comment by justinbmeyer** [comment]
@nlundquist Thinking about this a bit, is it a feature that `.preventDefault()` is not called?  If an error happens in someone's routing code (within the call to `history.pushstate()`) the app is very likely in a broken state.  Would it be better on average to do a full reload?

Is the problem that this situation is very hard to debug?

**Comment by nlundquist** [comment]
I agree the behavior is a nice fallback in production, but the reload it introduces is very noticeable and hard to debug. I think it should fail fast when in a development build.

In Ting's case this exception was being caught at some point in the CanJS call stack, so even preserving the log between reloads or breaking at navigation didn't reveal anything.
