### ISSUE TITLE
Docco notes

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-route-pushstate#135]
> It registers itself as binding on route, intercepts click events on <a> elements across document and accordingly updates route state and window’s pathname.

Avoid `it` and indefinite pronouns.  This should say something like https://github.com/canjs/can-route-pushstate/pull/128/files#diff-6ff0cfe12a8580703c9be3b06a5ee442R329

Also, it should talk about PushStateObservable inheriting from `SimpleObservable` and getting most of the "observable" logic from that.

**Comment by justinbmeyer** [comment]
> DISPATCHHANDLERS

> Updates this._value to the current url. PushstateObservable inherits from SimpleObservable which is using the can-event-queue/value/value mixin.

Why is inheritance relevant here? Maybe you are trying to talk about `can.dispatch`.  That's not clear from the language.  

Updating the value is really only part of this function.  The other important bit is that it dispatches event handlers on the object.

This should also talk about why this function would be called ... (as a result of calling history.pushstate)

Btw, I think this was supposed to cache `can.dispatch` symbol.

**Comment by justinbmeyer** [comment]
`var linksHost = node.host || window.location.host;`

I would generally put this code closer to where it matters ...

`if (window.location.host === linksHost) {`

**Comment by justinbmeyer** [comment]
> Test if you can preventDefault

Why might `.preventDefault()` not be there?

If you don't know ... write nothing ...

**Comment by justinbmeyer** [comment]
```
domEvents.addDelegateListener(document.documentElement, "click", "a", this.anchorClickHandler);
```

maybe this should be using `can-globals/document/document` to get the current document ...

**Comment by justinbmeyer** [comment]
> Initalizes this._value Sets up event listeners to capture click events on <a> elements. Overwrites the history api methods .pushState and .replaceState.

Missing a period?

**Comment by justinbmeyer** [comment]
> Adds PushstateObservable to the top of the stack and returns the current url.

What stack?

What this is really doing is making reading `PushstateObservable`s observable by `can-observation`s

**Comment by justinbmeyer** [comment]
> calls either pushState or replaceState on the difference in properties between oldProps and newProps.

Make sure all sentences start with `Capital` and end with a period.

**Comment by justinbmeyer** [comment]
> patch.key refers to the mutated property name on newProps.

This doesn't really describe what's going on here.  What's basically happening is the old state and the new state are diffed to figure out which keys are changing.  Depending if the keys are used in `replaceStateKeys` or `replaceStateOnceKeys`, `replaceState` will be used.

**Comment by justinbmeyer** [comment]
`var pushstateObservableProto = {`

is this needed?

**Comment by HTMLGhozt** [comment]
There's no other use of `"can.dispatch"` in the library, I'm not sure why there would be a need to cache it.

I'm not sure I understand:
> What this is really doing is making reading PushstateObservables observable by can-observations

The only reason I know of for testing `e.preventDefault` is browser compatibility, as it wasn't implemented in some older browsers.

The only use I could find for `paramsMatcher` is in `can-route` where it's either used to build regex or find substrings. added:
> or return url substrings of routes.

**Comment by justinbmeyer** [comment]
@HTMLGhozt It creates a slight performance benefit that probably isn't needed here, but helps in more heavily used code.

The following has to do 4 things:

```js
obj[Symbol.for("thing")]
```

1.  Lookup `Symbol`
2. Lookup .for
3. Call `.for`
4. Lookup the symbol on `obj`


This has to do 2:

```js
obj[thingSymbol]
```

1. Lookup `thingSymbol`
2. Lookup the symbol on `obj`

**Comment by HTMLGhozt** [comment]
#136 updates the documentation and refactors to fix the aforementioned issues.
