### ISSUE TITLE
anchorClickHandler fails on svg anchor tags

### ISSUE THREAD

**Issue by rob4acre** [canjs/can-route-pushstate#81]
The anchorClickHandler function fails when clicking on anchor tags in svg. e.g.

```
<a xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/things/1/description">
   <rect x="432.5" y="20" width="50" height="130" class="transponder"></rect>
</a>
```

It looks like the property **pathname** does not exist for svg anchor tags so this causes line 186 in v3.2.3 to fail. The equivalent property in SVG anchor tags looks like it is called **baseURI**

I'm not sure if canJS is supposed to support SVG but anyway, I thought I would raise this. I can of course, change the route in a function, but it seemed like an interesting thing to note.

**Comment by justinbmeyer** [comment]
this is a bug.  Thanks for reporting.
